on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
    - name: Read file if it exists?
      uses: mathiasvr/command-output@v2.0.0
      continue-on-error: true
      id: cmd
      with:
        run: cat unknown.txt
    
    - run: echo Command succeeded
      if: ${{ steps.cmd.outputs.stdout }}
    
    - run: |
        echo "errormessage=${{ steps.cmd.outputs.stderr }}" >> $GITHUB_OUTPUT
        exit 2
      if: ${{ steps.cmd.outputs.stderr }}
    
    - name: Get Date
      id: get_date
      run: |
        echo "now=$(date)" >> $GITHUB_OUTPUT 
        set +e
        echo "Hello World!" 2>&1 | tee -a output.log
        ls -l nofolder 2>&1 | tee -a output.log
        exitcode="$?"
        echo "errormessage=$(cat output.log | paste -s -d ":" -)" >> $GITHUB_OUTPUT
        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
  notify:
    needs: new_push_job
    if: always()
    runs-on: ubuntu-latest

    steps:
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        
        payload: |
          {
            "key": "value",
            "foo": "${{join(steps.get_date.outputs.*, '\n')}}"
          }
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/triggers/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
      
