on: [push]

jobs:
  new_push_job:
    runs-on: ubuntu-latest
    name: New push to repo
    steps:
    - name: Get Date
      id: get_date
      run: |
        echo "now=$(date)" >> $GITHUB_OUTPUT 
        set +e
        echo "err=$(ls -l nofolder) >> $GITHUB_OUTPUT
        exitcode="$?"
        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
        
    - name: Send GitHub trigger payload to Slack Workflow Builder
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "key": "value",
            "foo": "${{join(steps.get_date.outputs.*, '\n')}}"
          }
      env:
        SLACK_WEBHOOK_URL: https://hooks.slack.com/triggers/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
      
